version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16-browsers
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - run: npm install -g @lhci/cli@0.3.x
      - run:
          name: lhci autorun
          command: lhci autorun
